### ISSUE TITLE
Menu doesn't work

### ISSUE THREAD

**Issue by JukoiDev** [xnst0/ichigo_ui#1]
Menu doesn't work in game(the match). Also I need your Discord ;)

**Comment by JukoiDev** [comment]
in match

**Comment by JukoiDev** [comment]
FIX:

hooks.cpp

		if (GetAsyncKeyState(VK_INSERT) & 1)
			menu::opened = !menu::opened;

**Comment by xnst0** [comment]
add me at 
Ichigo#0001

menu should open in game as i was testing yesterday in game for keybinds and stuff

**Comment by xnst0** [comment]
im pretty sure its because of the GetForegroundWindow() check, i'll remove it and add something else to prevent the window from toggling when you're not focussed on the game.
