### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by 0xa00** [xnst0/ichigo_ui#3]
you're querying the window title maybe 200 times a second
do you think this is "optimal"?
https://github.com/xnst0/ichigo_ui/blob/d60a6e00fe6f30488cf33d2d28243cebdfbd8a49/full%20base/core/menu/menu.cpp#L52
also what the fuck..
https://github.com/xnst0/ichigo_ui/blob/d60a6e00fe6f30488cf33d2d28243cebdfbd8a49/full%20base/core/menu/menu.cpp#L49

**Comment by maostrafes** [comment]
cry more fag

**Comment by xnst0** [comment]
the spotify thing is ghetto and not even by me so i literally couldnt care less.

**Comment by 0xa00** [comment]
> 
> 
> the spotify thing is ghetto and not even by me so i literally couldnt care less.

stop getting defensive and fix your pasta hack, I posted this with good intentions, you should care since that will drop your fps to 40

**Comment by xnst0** [comment]
> > the spotify thing is ghetto and not even by me so i literally couldnt care less.
> 
> stop getting defensive and fix your pasta hack, I posted this with good intentions, you should care since that will drop your fps to 40

its literally not a hack but ok. and i dont drop to 40 fps with it so. the only thing i really did on this was make the gui foldert and do pretty much everything in there apart from the imgui files etc
